# Generated by Django 3.2.18 on 2025-07-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('payPerDay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('contractorContact', models.CharField(max_length=20)),
                ('status', models.CharField(default='open', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('userType', models.CharField(choices=[('daily', 'Daily'), ('skilled', 'Skilled')], default='daily', max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('phoneNumber', models.CharField(max_length=20, null=True, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dailyJobTypes', models.JSONField(blank=True, default=list, null=True)),
                ('profilePhotoUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('ipfsHash', models.CharField(blank=True, max_length=200, null=True)),
                ('averageRating', models.FloatField(default=0.0)),
                ('jobsCompleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='worker.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='worker.user')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='postedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='worker.user'),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.CharField(default='Pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.user')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
