# Generated by Django 3.2.18 on 2025-07-21 03:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='work_history',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
