# Generated by Django 3.2.18 on 2025-07-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dailyJobTypes',
            new_name='JobTypes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pincode',
            new_name='pinCode',
        ),
    ]
