# Generated by Django 5.1.5 on 2025-07-28 19:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_auto_20250728_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="experienceYears",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="totalEarnings",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verificationLevel",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("verified", "Verified"),
                    ("premium", "Premium"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("government", "Government Issued"),
                            ("ngo", "NGO Training"),
                            ("private", "Private Institution"),
                            ("reference", "Job Reference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("imageUrl", models.URLField(max_length=500)),
                ("isVerified", models.BooleanField(default=False)),
                ("verificationData", models.JSONField(blank=True, default=dict)),
                ("uploadedAt", models.DateTimeField(auto_now_add=True)),
                ("verifiedAt", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="worker.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("imageUrl", models.URLField(max_length=500)),
                ("location", models.CharField(max_length=200)),
                ("completedAt", models.DateField()),
                ("skills", models.JSONField(default=list)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="worker.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("earnings", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.job"
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worker.rating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_history",
                        to="worker.user",
                    ),
                ),
            ],
        ),
    ]
